# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: The Works of Stuart Butler
# Description of the Site
description: Games Developer and Academic
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: UE5, StuButler, Stuart Butler, gamesdev, tutorials, 3dart
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/heroBG.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: stu@thundersteed.co.uk
facebook_username: 
twitter_username: stu3dart
instagram_username: stubutler
linkedin_username: stubutler
github_username: stubutler
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username:
unreal_username: StuButler

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Stuart Butler
# URL for the Image of the Author
author-image: https://ue-cdn.artstation.com/imgproxy/c2wlu2RXwvxoT2AV4XM98wgZ1KdZcxbSuXVqzDhkdRs/filename:1653466894136.jpg/resizing_type:fit/width:800/height:800/aHR0cHM6Ly9kMWl2N2RiNDR5aGd4bi5jbG91ZGZyb250Lm5ldC9hdmF0YXJzLzMzZGVmYzhhLWFmYTMtNDUyMS1hZGQ0LWNhOTkwZjg1NmViZS8xNjUzNDY2ODk0MTM2LmpwZw
# 60 Words About the Author
author-about: Course Director of Games Technology at Staffordshire University and Authorized Unreal Instructor.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/stubutler

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
